### ISSUE TITLE
404 on link to Cookiecutter Project Template

### ISSUE THREAD

**Issue by BrianBorge** [customink/cookiecutter-ruby-workshop#1]
When clicking on the link, "Cookiecutter  Project Template", found [here ](https://github.com/customink/cookiecutter-ruby-workshop/blob/master/1-sam-init.md#sam-init), I am sent to a 404 page on GitHub pages. 

Here's the url (404): https://technology.customink.com/blog/2020/03/13/using-aws-sam-cookiecutter-project-templates-to-kickstart-your-ambda-projects-copy

I did some digging and found this blog post on the custom ink site which seems to be the post the workshop is trying to send readers to -> https://technology.customink.com/blog/2020/03/13/using-aws-sam-cookiecutter-project-templates-to-kickstart-your-ambda-projects/

Two things I noticed with the url in the workshop readme page: "lambda" is misspelled and there is a "-copy" at the end.  Probably an oversight and super minor but just reporting the issue as I came across it reading the workshop 😃 .

**Comment by metaskills** [comment]
Thanks! Pushed up a fix to the repo, not the blog slug. I saw that too and it is kind of a pain to do redirects in Jekyll. FYI, the articles are here now too.

* https://dev.to/aws-heroes/aws-lambda-microservice-workshop-using-s3-libvips-ruby-4o96
* https://dev.to/metaskills/using-aws-sam-cookiecutter-project-templates-37le

Please do let me know if you liked them and thanks again for taking the time to help!

**Comment by BrianBorge** [comment]
Awesome! I'll check out the dev.to posts and ask any questions there.  

> Please do let me know if you liked them and thanks again for taking the time to help!

They are very helpful, especially the parts about the connection between SAM Template and Cloudformation.  Also happy to help.
